version: "3.9"

services:
  db:
    image: mysql:8.0.26
    restart: always
    ports:
    - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: schwingen
  api:
    image: 70131370/schwingen:1.0.0-SNAPSHOT
    restart: always
    ports:
      - 8080:8080
